export const demoGigs = [
  {
    _id: "demo-gig-1",
    title: "I will design a polished landing page for your startup",
    category: "design",
    description:
      "Need a high-converting landing page that looks modern and feels premium? I design responsive student-built websites with clear hierarchy, persuasive copy structure, and Figma-ready delivery.",
    tags: ["Figma", "Landing Page", "UX Audit", "Responsive"],
    rating: 4.9,
    reviewCount: 38,
    orderCount: 21,
    viewCount: 540,
    seller: {
      _id: "demo-user-1",
      name: "Aanya Mehta",
      university: "IIT Guwahati",
      avatar: "",
      rating: 4.9,
      isOnline: true,
      isVerified: true,
      bio: "Product design student helping startups turn rough ideas into clean, convincing interfaces.",
      skills: ["Figma", "UX Research", "Design Systems"],
    },
    pricing: {
      basic: {
        title: "Starter",
        description: "One landing page concept",
        price: 2500,
        deliveryDays: 3,
        features: ["Responsive layout", "Hero section", "CTA-focused flow"],
      },
      standard: {
        title: "Launch",
        description: "Multi-section polished page",
        price: 5500,
        deliveryDays: 5,
        features: ["Complete layout", "Design system tokens", "2 revision rounds"],
      },
      premium: {
        title: "Scale",
        description: "Full landing page plus assets",
        price: 9000,
        deliveryDays: 7,
        features: ["Full desktop + mobile", "Copy suggestions", "Prototype interactions"],
      },
    },
  },
  {
    _id: "demo-gig-2",
    title: "I will build your MERN dashboard with charts and auth",
    category: "web-development",
    description:
      "From admin panels to founder dashboards, I build fast full-stack web apps with Express APIs, MongoDB, and polished responsive interfaces.",
    tags: ["MERN", "Dashboard", "API", "MongoDB"],
    rating: 4.8,
    reviewCount: 29,
    orderCount: 18,
    viewCount: 420,
    seller: {
      _id: "demo-user-2",
      name: "Arjun Singh",
      university: "NIT Trichy",
      avatar: "",
      rating: 4.8,
      isOnline: false,
      isVerified: true,
      bio: "Full-stack engineering student focused on shipping reliable product MVPs.",
      skills: ["Node.js", "MongoDB", "Vanilla JS", "React"],
    },
    pricing: {
      basic: {
        title: "Basic",
        description: "Single dashboard view",
        price: 6000,
        deliveryDays: 5,
        features: ["Auth flow", "One chart", "Responsive layout"],
      },
      standard: {
        title: "Growth",
        description: "Multi-page admin build",
        price: 12000,
        deliveryDays: 8,
        features: ["3 dashboard views", "REST API", "Role-based access"],
      },
      premium: {
        title: "Product",
        description: "Complete analytics dashboard",
        price: 22000,
        deliveryDays: 12,
        features: ["Realtime widgets", "Deployment help", "QA support"],
      },
    },
  },
  {
    _id: "demo-gig-3",
    title: "I will edit cinematic reels and short-form videos",
    category: "video-editing",
    description:
      "Short-form content that feels sharp, energetic, and ready to post. Ideal for campus creators, clubs, startups, and student founders.",
    tags: ["Premiere Pro", "Reels", "Motion Graphics"],
    rating: 4.7,
    reviewCount: 19,
    orderCount: 14,
    viewCount: 290,
    seller: {
      _id: "demo-user-3",
      name: "Sarah Nair",
      university: "Christ University",
      avatar: "",
      rating: 4.7,
      isOnline: true,
      isVerified: true,
      bio: "Media student editing for founders, clubs, creators, and events.",
      skills: ["Premiere Pro", "After Effects", "Sound Design"],
    },
    pricing: {
      basic: {
        title: "Quick Cut",
        description: "One edited reel",
        price: 1800,
        deliveryDays: 2,
        features: ["Cuts and pacing", "Captions", "Audio cleanup"],
      },
      standard: {
        title: "Creator Pack",
        description: "Three edited reels",
        price: 4200,
        deliveryDays: 4,
        features: ["3 edits", "Motion titles", "Hook-first flow"],
      },
      premium: {
        title: "Campaign",
        description: "Five premium edits",
        price: 7600,
        deliveryDays: 6,
        features: ["5 edits", "Branding overlays", "Platform exports"],
      },
    },
  },
  {
    _id: "demo-gig-4",
    title: "I will write SEO blog content with strong research",
    category: "writing",
    description:
      "Well-researched, voice-aware articles built to rank and still read like a human wrote them. Great for student startups and niche products.",
    tags: ["SEO", "Blog Writing", "Research", "Editing"],
    rating: 4.9,
    reviewCount: 24,
    orderCount: 16,
    viewCount: 315,
    seller: {
      _id: "demo-user-4",
      name: "Ritika Sharma",
      university: "Delhi University",
      avatar: "",
      rating: 4.9,
      isOnline: false,
      isVerified: true,
      bio: "Writer and editor helping young brands sound credible, clear, and useful.",
      skills: ["Content Strategy", "SEO", "Editing"],
    },
    pricing: {
      basic: {
        title: "Article",
        description: "One 800-word SEO post",
        price: 1200,
        deliveryDays: 2,
        features: ["Keyword alignment", "Proofread", "Clean formatting"],
      },
      standard: {
        title: "Content Pack",
        description: "Three SEO posts",
        price: 3400,
        deliveryDays: 5,
        features: ["3 articles", "Topic research", "Meta descriptions"],
      },
      premium: {
        title: "Editorial Sprint",
        description: "Five researched posts",
        price: 5900,
        deliveryDays: 7,
        features: ["5 posts", "Internal linking ideas", "Content angle planning"],
      },
    },
  },
  {
    _id: "demo-gig-5",
    title: "I will analyze your data and build a clean dashboard",
    category: "data-science",
    description:
      "Turn raw spreadsheets into dashboards, insights, and decision-ready narratives using Python, SQL, and clear visual communication.",
    tags: ["Python", "Dashboards", "Analytics", "Pandas"],
    rating: 4.8,
    reviewCount: 15,
    orderCount: 10,
    viewCount: 210,
    seller: {
      _id: "demo-user-5",
      name: "Kabir Patel",
      university: "BITS Pilani",
      avatar: "",
      rating: 4.8,
      isOnline: true,
      isVerified: true,
      bio: "Data science student turning messy data into crisp business stories.",
      skills: ["Python", "Pandas", "SQL", "Tableau"],
    },
    pricing: {
      basic: {
        title: "Snapshot",
        description: "Quick exploratory analysis",
        price: 2200,
        deliveryDays: 3,
        features: ["Data cleaning", "Summary insights", "Charts"],
      },
      standard: {
        title: "Insight Pack",
        description: "Dashboard plus recommendations",
        price: 5200,
        deliveryDays: 5,
        features: ["Interactive visuals", "KPI summary", "Annotated notebook"],
      },
      premium: {
        title: "Decision Studio",
        description: "Advanced analysis workflow",
        price: 9800,
        deliveryDays: 8,
        features: ["Advanced segmentation", "Presentation-ready summary", "Delivery walkthrough"],
      },
    },
  },
];

export const demoReviews = [
  {
    reviewer: "Neha Verma",
    rating: 5,
    text: "Clear communication, smooth revisions, and a final delivery that looked far more premium than we expected for the price.",
    createdAt: "2026-04-18T10:00:00.000Z",
  },
  {
    reviewer: "Marcus Lee",
    rating: 5,
    text: "The seller moved quickly, understood the brief well, and gave us a project we could actually launch.",
    createdAt: "2026-04-12T14:30:00.000Z",
  },
  {
    reviewer: "Ishita Rao",
    rating: 4,
    text: "Professional work and very responsive. I would hire again for follow-up improvements.",
    createdAt: "2026-03-29T09:20:00.000Z",
  },
];

export const demoOrders = [
  {
    _id: "demo-order-1",
    status: "active",
    price: 5500,
    tier: "standard",
    createdAt: "2026-04-22T08:00:00.000Z",
    deliveryDate: "2026-04-30T08:00:00.000Z",
    gig: { _id: "demo-gig-1", title: "Startup landing page redesign" },
    buyer: { _id: "buyer-1", name: "Akash Jain" },
    seller: { _id: "demo-user-1", name: "Aanya Mehta" },
  },
  {
    _id: "demo-order-2",
    status: "delivered",
    price: 12000,
    tier: "standard",
    createdAt: "2026-04-19T08:00:00.000Z",
    deliveryDate: "2026-04-27T08:00:00.000Z",
    gig: { _id: "demo-gig-2", title: "MERN analytics dashboard" },
    buyer: { _id: "buyer-2", name: "Campus Commerce Club" },
    seller: { _id: "demo-user-2", name: "Arjun Singh" },
  },
  {
    _id: "demo-order-3",
    status: "completed",
    price: 4200,
    tier: "standard",
    createdAt: "2026-04-11T08:00:00.000Z",
    deliveryDate: "2026-04-16T08:00:00.000Z",
    gig: { _id: "demo-gig-3", title: "Cinematic reels pack" },
    buyer: { _id: "buyer-3", name: "Founders Society" },
    seller: { _id: "demo-user-3", name: "Sarah Nair" },
  },
];

export const demoConversations = [
  {
    conversationId: "demo-user-1_demo-user-2",
    otherUser: {
      _id: "demo-user-1",
      name: "Aanya Mehta",
      avatar: "",
      isOnline: true,
      lastSeen: "2026-04-27T07:00:00.000Z",
    },
    lastMessage: "I can send the updated Figma link in the next hour.",
    lastMessageDate: "2026-04-27T06:50:00.000Z",
    unreadCount: 2,
  },
  {
    conversationId: "demo-user-3_demo-user-2",
    otherUser: {
      _id: "demo-user-3",
      name: "Sarah Nair",
      avatar: "",
      isOnline: false,
      lastSeen: "2026-04-26T13:10:00.000Z",
    },
    lastMessage: "Can you confirm the final export dimensions?",
    lastMessageDate: "2026-04-26T13:10:00.000Z",
    unreadCount: 0,
  },
];

export const demoMessages = {
  "demo-user-1_demo-user-2": [
    {
      _id: "m1",
      sender: "demo-user-1",
      receiver: "demo-user-2",
      text: "I reviewed your notes and I can tighten the hero section layout.",
      createdAt: "2026-04-27T06:20:00.000Z",
    },
    {
      _id: "m2",
      sender: "demo-user-2",
      receiver: "demo-user-1",
      text: "Perfect. Could you also make the CTA feel more prominent?",
      createdAt: "2026-04-27T06:28:00.000Z",
    },
    {
      _id: "m3",
      sender: "demo-user-1",
      receiver: "demo-user-2",
      text: "I can send the updated Figma link in the next hour.",
      createdAt: "2026-04-27T06:50:00.000Z",
    },
  ],
  "demo-user-3_demo-user-2": [
    {
      _id: "m4",
      sender: "demo-user-2",
      receiver: "demo-user-3",
      text: "The reel pacing looks good. Can you confirm the final export dimensions?",
      createdAt: "2026-04-26T13:10:00.000Z",
    },
  ],
};

export const demoProfile = {
  _id: "demo-user-2",
  name: "Arjun Singh",
  email: "arjun@nit.edu",
  role: "seller",
  university: "NIT Trichy",
  avatar: "",
  bio: "Full-stack engineering student building practical dashboards, MVPs, and web products for founders, clubs, and campus communities.",
  skills: ["Node.js", "MongoDB", "Express", "Vanilla JS", "UI Systems"],
  isVerified: true,
  verificationStatus: "verified",
  createdAt: "2024-08-12T09:00:00.000Z",
  rating: 4.8,
  reviewCount: 29,
};

export const demoAnalytics = {
  dashboard: {
    totalEarnings: 48500,
    activeOrders: 8,
    completedOrders: 24,
    pendingOrders: 3,
    totalOrders: 35,
    avgRating: 4.9,
    totalViews: 1240,
    conversionRate: 12.6,
  },
  monthly: [
    { label: "May", earnings: 0, orders: 0 },
    { label: "Jun", earnings: 0, orders: 0 },
    { label: "Jul", earnings: 0, orders: 0 },
    { label: "Aug", earnings: 4200, orders: 2 },
    { label: "Sep", earnings: 6200, orders: 3 },
    { label: "Oct", earnings: 5800, orders: 2 },
    { label: "Nov", earnings: 7500, orders: 4 },
    { label: "Dec", earnings: 6900, orders: 3 },
    { label: "Jan", earnings: 4100, orders: 2 },
    { label: "Feb", earnings: 5600, orders: 3 },
    { label: "Mar", earnings: 7200, orders: 4 },
    { label: "Apr", earnings: 11000, orders: 5 },
  ],
  weekly: [
    { label: "W10", earnings: 1500, orders: 1 },
    { label: "W11", earnings: 2100, orders: 1 },
    { label: "W12", earnings: 3600, orders: 2 },
    { label: "W13", earnings: 2800, orders: 2 },
    { label: "W14", earnings: 3200, orders: 2 },
    { label: "W15", earnings: 4200, orders: 2 },
    { label: "W16", earnings: 5100, orders: 3 },
    { label: "W17", earnings: 6200, orders: 3 },
  ],
  performance: [
    {
      _id: "demo-gig-2",
      title: "MERN analytics dashboard",
      price: 12000,
      rating: 4.8,
      reviewCount: 29,
      orderCount: 18,
      viewCount: 420,
      conversionRate: 4.3,
      isActive: true,
    },
    {
      _id: "demo-gig-1",
      title: "Landing page design sprint",
      price: 5500,
      rating: 4.9,
      reviewCount: 38,
      orderCount: 21,
      viewCount: 540,
      conversionRate: 3.9,
      isActive: true,
    },
    {
      _id: "demo-gig-3",
      title: "Cinematic reels pack",
      price: 4200,
      rating: 4.7,
      reviewCount: 19,
      orderCount: 14,
      viewCount: 290,
      conversionRate: 4.8,
      isActive: true,
    },
  ],
};
